### ISSUE TITLE
Cannot get bus

### ISSUE THREAD

**Issue by brandondb1** [OpenBekenIOT/hid_download_py#5]
Hello,

I have a light switch with a BK7231N chip.  When I run the Python programming tool, I get an error Cannot Get Bus.

The chip is directly soldered onto the board, and the board itself has a 6-slot programming header with 2 pins labelled R, and one labelled T...both of the R pins connect to the chip, and I can't find a chip-level pinout for the 7231N, so either could be Receive.

I've tried switching leads from one R to the other, but get the same error either way.

My question is what the Cannot Get Bus error means - is it an issue with my R and T pins, a hardware issue with my USB adapter, or...?  I have programmed literally hundreds of ESPs, so I am very familiar with the concept.  I'm just trying to understand the error so I can focus my efforts on the actual problem.  Running in a Python VENV, COM port for the USB-UART is correct, and switch has power (LED's light and I am using 3.3v)

Also if anyone has or knows where a chip-level pinout diagram can be found I would be very appreciative.

Thanks in advance.

**Comment by brandondb1** [comment]
OK.  I figured it out:

I found a pin map for the chip, and identified which R on the header was Receive.  The other R was Reset.

Executed the uartprogram python command, when it says 'Getting Bus' I shorted the Reset to ground and it programmed immediately.

For some reason the detail of shorting the Reset gets lost in Google translation from the elektroda posts...

Thanks for your work on this!

**Comment by yarix** [comment]
got same\similar problem when trying to read from CB3S chip.
i also tried to reset pin1 to ground when asking for "Getting Bus", but it didn't help.
any idea?

```
(py37-env) C:\repo\hid_download_py>python uartprogram y.bin -r -d com9
UartDownloader....
Read Getting Bus...
Cannot get bus.
Traceback (most recent call last):
  File "uartprogram", line 56, in <module>
    downloader.read(args.filename, args.startaddr, args.length)
  File "C:\repo\hid_download_py\bkutils\uart_downloader.py", line 83, in read
    self.pbar.close()
AttributeError: 'NoneType' object has no attribute 'close'
```
